//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo2_Cities.Resources.Texts {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CitiesDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CitiesDetail() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modulo2_Cities.Resources.Texts.CitiesDetail", typeof(CitiesDetail).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva York es la ciudad más poblada del estado homónimo y de los Estados Unidos de América, y la tercera mayor concentración urbana del continente americano, después de Sao Paulo (Brasil) y la Ciudad de México. La ciudad de Nueva York está entre las aglomeraciones urbanas más grandes y más pobladas del mundo.4
        ///
        ///Desde finales del siglo XIX es uno de los principales centros de comercio y finanzas del mundo. Nueva York está considerada como ciudad global, dadas sus influencias a nivel mundial en los medios d [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string NewYok {
            get {
                return ResourceManager.GetString("NewYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a París es la capital de Francia y su ciudad más poblada. Capital de la región de Isla de Francia (o &quot;Región Parisina&quot;), es constituida en la única comuna unidepartamental del país. Está situada a ambos márgenes de un largo meandro del río Sena, en el centro de la Cuenca parisina, entre la confluencia del río Marne y el Sena, aguas arriba, y el Oise y el Sena, aguas abajo.
        ///
        ///La ciudad de París, dentro de sus estrechos límites administrativos, tiene una población de 2 273 305 habitantes en 2015.2 Sin embargo, [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Paris {
            get {
                return ResourceManager.GetString("Paris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roma es una ciudad y capital italiana, de 2 872 082 habitantes,1 2 capital de la Ciudad metropolitana de Roma Capital, de la región del Lacio y de Italia. Es el municipio más poblado de Italia y es la cuarta ciudad más poblada de la Unión Europea.3 Por antonomasia se la conoce como la Ciudad Eterna, l&apos;Urbe (‘la Ciudad’) o Città Eterna.
        ///
        ///En el transcurso de su historia, que abarca tres milenios, llegó a extender sus dominios sobre toda la cuenca del Mediterráneo y gran parte de Europa. Como capital del Imp [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Roma {
            get {
                return ResourceManager.GetString("Roma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a San Francisco, de forma oficial la Ciudad y Condado de San Francisco (en inglés: City and County of San Francisco), es una ciudad que ocupa la cuarta posición de ciudad más poblada del estado de California y la 13.ª de Estados Unidos, con una población de aproximadamente 837 442 habitantes en 2013.6 Es la única ciudad-condado consolidada de California, y al abarcar una superficie territorial de 121 km² cuenta con la segunda densidad de población más alta del país entre las ciudades que superan los 200 000 h [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string SanFrancisco {
            get {
                return ResourceManager.GetString("SanFrancisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seattle es la ciudad más grande del estado de Washington, en el noroeste de los Estados Unidos de América. El área metropolitana de la ciudad comprende Seattle-Tacoma-Bellevue, es la 15.ª más poblada del país y la mayor del Noroeste del Pacífico.5 La ciudad está situada entre el lago Washington y la bahía conocida como Puget Sound, junto al océano Pacífico. Se encuentra 155 kilómetros al sur de la frontera entre Estados Unidos y Canadá. Importante centro cultural, educativo y económico de la región, Seattle [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Seattle {
            get {
                return ResourceManager.GetString("Seattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sevilla es un municipio y una ciudad de España, capital de la provincia homónima y de la comunidad autónoma de Andalucía.5 Cuenta con 693 878 habitantes en 2015,6 por lo que es la ciudad más poblada de Andalucía, la cuarta de España7 después de Madrid, Barcelona y Valencia y la 32.ª de la Unión Europea. El municipio tiene una extensión de 140,8 km².8 El área metropolitana de Sevilla está compuesta por 46 municipios, incluye a una población de 1 533 230 habitantes (INE, 2014), y ocupa una superficie de 4900  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Sevilla {
            get {
                return ResourceManager.GetString("Sevilla", resourceCulture);
            }
        }
    }
}
