//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo2_Cities.Droid
***REMOVED***


    public partial class Resource
    ***REMOVED***

        public partial class Attribute
        ***REMOVED***

            private Attribute()
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***

        public partial class Drawable
        ***REMOVED***

            // aapt resource value: 0x7f020000
            public const int Icon = 2130837504;

            private Drawable()
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***

        public partial class Id
        ***REMOVED***

            // aapt resource value: 0x7f050000
            public const int MyButton = 2131034112;

            private Id()
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***

        public partial class Layout
        ***REMOVED***

            // aapt resource value: 0x7f030000
            public const int Main = 2130903040;

            private Layout()
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***

        public partial class String
        ***REMOVED***

            // aapt resource value: 0x7f040001
            public const int ApplicationName = 2130968577;

            // aapt resource value: 0x7f040000
            public const int Hello = 2130968576;

            private String()
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***
***REMOVED***
***REMOVED***
